%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_FilterFactory
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTERFACTORY_HRL).
-define(COSNOTIFYFILTER_FILTERFACTORY_HRL, true).




-endif.


