language: node_js
node_js: stable

addons:
  apt:
    packages:
    - sshpass

branches:
  only:
  - master
  
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
env:
  - PUSH_BRANCH="travic_upload"  PUSH_DIRNAME="travic_upload" ARTIFACTS_PROD="wicc-waykimix.tar.gz" TAR_NAME="dist"
 
  
install:
  - npm install
  
script:
  - npm run build
  
after_script:
  - ls 
  - echo ${ARTIFACTS_PROD}
  - echo ${TAR_NAME}
  - tar zcf ${ARTIFACTS_PROD} ${TAR_NAME}
  - mkdir ${PUSH_DIRNAME}
  - ls
  - cp -a ${ARTIFACTS_PROD} ${PUSH_DIRNAME}
  - cd ${PUSH_DIRNAME}
  - pwd
  - ls
  - sshpass -p ${DEPLOY_PASS} scp -o stricthostkeychecking=no -p ${DEPLOY_PORT} -r ${ARTIFACTS_PROD} ${DEPLOY_USER}@${DEPLOY_HOST}:/tmp
  
