language: node_js
node_js: stable

branches:
  only:
  - master
  
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
    
install:
  - npm install
  
script:
  - npm run build
  
after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git remote add origin-pages https://${GITHUB_TOKEN}@${GITHUB_ORIGIN} > /dev/null 2>&1
  - git push --quiet --set-upstream origin-pages ${PUSH_BRANCH}
  
