language: node_js
node_js: stable

branches:
  only:
  - master
  
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
env:
  - PUSH_BRANCH=travic_upload
  - PUSH_DIRNAME=travic_upload
  - ARTIFACTS_PROD=wicc-waykimix.tar.gz
  - TAR_NAME=dist
  
install:
  - npm install
  
script:
  - npm run build
  
after_script:
  - tar zcf ${ARTIFACTS_PROD} ${TAR_NAME}
  - mkdir ${PUSH_DIRNAME}
  - cp -a ${ARTIFACTS_PROD} ${PUSH_DIRNAME}
  - cd ${PUSH_DIRNAME}
  - git init
  - git checkout -b ${PUSH_BRANCH}
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git remote add origin https://${GITHUB_TOKEN}@${GITHUB_ORIGIN}
  - git push --quiet --set-upstream --force origin ${PUSH_BRANCH}
  
