language: node_js
node_js: stable

branches:
  only:
  - master
  
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
    
install:
  - npm install
  
script:
  - npm run build
  
after_script:
  - cd ./dist
  - pwd
  - ls
  - git init
  - git checkout -b ${PUSH_BRANCH}
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git remote add origin https://${GITHUB_TOKEN}@${GITHUB_ORIGIN}
  - git remote -v 
  - git push --quiet --set-upstream --force origin ${PUSH_BRANCH}
  
