%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertiesIterator
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL).
-define(COSPROPERTYSERVICE_PROPERTIESITERATOR_HRL, true).




-endif.


