%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPushSupplier
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL, true).




-endif.


