%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_CAdmin
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_CADMIN_HRL).
-define(OE_COSEVENTCOMM_CADMIN_HRL, true).




-endif.


