#!/usr/bin/env bash

if
  [[ -s "/home/travis/.rvm/gems/ruby-2.4.1/environment" ]]
then
  source "/home/travis/.rvm/gems/ruby-2.4.1/environment"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/travis/.rvm/gems/ruby-2.4.1/environment'" >&2
  exit 1
fi
