#!/bin/bash
if [[ "${rvm_ruby_string}" =~ "truffleruby" ]]; then
  # TruffleRuby always has a more recent RubyGems than 2.6.13.
  return 0
fi
gem --help &>/dev/null || return 0

travis_vers2int() {
  local args
  read -r -a args <<<"$(echo "${1}" | grep --only '^[0-9\.][0-9\.]*' | tr '.' ' ')"
  printf '1%03d%03d%03d%03d' "${args[@]}"
}


if [[ "$(travis_vers2int "$(gem --version)")" -lt "$(travis_vers2int "2.6.13")" ]]; then
  echo ""
  echo -e "\033[32;1m** Updating RubyGems to the latest compatible version for security reasons. **\033[0m"
  echo -e "\033[32;1m** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **\033[0m"
  echo ""
  if [[ "$(travis_vers2int "$(ruby -e 'puts RUBY_VERSION')")" -lt "$(travis_vers2int "2.3.0")" ]]; then
    gem update --system 2.7.8 &>/dev/null
  else
    gem update --system &>/dev/null
  fi
fi

