%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_RecoveryCoordinator
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL).
-define(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL, true).




-endif.


