%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_File
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILE_HRL).
-define(COSFILETRANSFER_FILE_HRL, true).




-endif.


