%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CORBA
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/orber/src/CORBA.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_CORBA_HRL).
-define(OE_CORBA_HRL, true).




-endif.


