%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_HRL).
-define(ORBERAPP_HRL, true).




-endif.


