%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_erlang
%% Source: /home/travis/.kerl/builds/19.3/otp_src_19.3/lib/ic/include/erlang.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ERLANG_HRL).
-define(OE_ERLANG_HRL, true).




-endif.


